id: weekly-summary
namespace: continuous-docs

description: Weekly code diff summarization using Kestra AI Agent

inputs:
  - id: repo_url
    type: STRING
    defaults: https://github.com/YOUR_USERNAME/continuous-docs-generator

  - id: openai_api_key
    type: SECRET
    
  - id: github_token
    type: SECRET

variables:
  days_back: 7

tasks:
  # Task 1: Fetch Git Diffs
  - id: fetch_git_diffs
    type: io.kestra.plugin.git.Clone
    url: "{{ inputs.repo_url }}"
    branch: main

  - id: get_recent_commits
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - git log --since="{{ vars.days_back }} days ago" --pretty=format:"%H|%an|%ad|%s" > commits.txt
      - git diff HEAD~{{ vars.days_back }}..HEAD > changes.diff

  # Task 2: Read diff data
  - id: read_diff_file
    type: io.kestra.plugin.core.storage.LocalFiles
    inputs:
      changes.diff: "{{ outputs.get_recent_commits.outputFiles['changes.diff'] }}"

  # Task 3: Summarize using Kestra AI Agent
  - id: summarize_changes
    type: io.kestra.plugin.openai.ChatCompletion
    apiKey: "{{ secret('OPENAI_API_KEY') }}"
    model: gpt-4-turbo-preview
    messages:
      - role: system
        content: |
          You are a technical documentation AI agent integrated with Kestra workflow orchestration.
          Your job is to analyze git diffs and commit history, then create a comprehensive weekly summary.
          
          Provide:
          1. Executive Summary (2-3 sentences)
          2. Major Changes (features, improvements)
          3. Bug Fixes
          4. Breaking Changes (if any)
          5. Files Modified (top 10)
          6. Recommendations for documentation updates
          
          Make it readable for both technical and non-technical stakeholders.
          
      - role: user
        content: |
          Analyze the following git diff and commits from the past {{ vars.days_back }} days:
          
          COMMITS:
          {{ outputs.get_recent_commits.outputFiles['commits.txt'] }}
          
          DIFF:
          {{ outputs.get_recent_commits.outputFiles['changes.diff'] }}
          
          Generate a comprehensive weekly summary report.

  # Task 4: Make decisions based on summary (Bonus feature!)
  - id: analyze_impact
    type: io.kestra.plugin.openai.ChatCompletion
    apiKey: "{{ secret('OPENAI_API_KEY') }}"
    model: gpt-4-turbo-preview
    messages:
      - role: system
        content: |
          You are an AI agent that makes decisions about documentation needs.
          Based on code changes, determine:
          1. Does this require API doc updates? (YES/NO + reason)
          2. Does this require architecture diagram updates? (YES/NO + reason)
          3. Should we trigger a documentation rebuild? (YES/NO + reason)
          4. Urgency level: LOW/MEDIUM/HIGH
          
          Respond in JSON format:
          {
            "api_docs_update": {"required": boolean, "reason": string},
            "architecture_update": {"required": boolean, "reason": string},
            "rebuild_needed": boolean,
            "urgency": string,
            "recommended_actions": [string]
          }
          
      - role: user
        content: |
          Based on this weekly summary, what documentation actions are needed?
          
          {{ outputs.summarize_changes.choices[0].message.content }}

  # Task 5: Create summary document
  - id: create_summary_markdown
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - |
        cat << 'EOF' > weekly-summary-$(date +%Y-%m-%d).md
        # Weekly Summary - $(date +%Y-%m-%d)
        
        ## AI-Generated Summary
        
        {{ outputs.summarize_changes.choices[0].message.content }}
        
        ---
        
        ## AI Decision Analysis
        
        {{ outputs.analyze_impact.choices[0].message.content }}
        
        ---
        
        *Generated automatically by Kestra AI Agent*
        EOF

  # Task 6: Commit summary to repository
  - id: commit_summary
    type: io.kestra.plugin.git.Push
    url: "{{ inputs.repo_url }}"
    branch: weekly-summaries
    commitMessage: "📊 Weekly summary - $(date +%Y-%m-%d)"
    files:
      - weekly-summary-*.md
    username: kestra-bot
    password: "{{ secret('GITHUB_TOKEN') }}"

  # Task 7: Create PR for review
  - id: create_pull_request
    type: io.kestra.plugin.scripts.shell.Commands
    env:
      GITHUB_TOKEN: "{{ secret('GITHUB_TOKEN') }}"
    commands:
      - |
        gh pr create \
          --title "📊 Weekly Documentation Summary - $(date +%Y-%m-%d)" \
          --body "Automated weekly summary generated by Kestra AI Agent. This PR includes analysis of code changes from the past {{ vars.days_back }} days and recommendations for documentation updates." \
          --base main \
          --head weekly-summaries

  # Task 8: Trigger documentation rebuild if needed
  - id: conditional_rebuild
    type: io.kestra.plugin.core.flow.If
    condition: "{{ outputs.analyze_impact.choices[0].message.content contains 'rebuild_needed\": true' }}"
    then:
      - id: trigger_doc_rebuild
        type: io.kestra.plugin.core.http.Request
        uri: https://api.vercel.com/v1/deployments
        method: POST
        headers:
          Authorization: "Bearer {{ secret('VERCEL_TOKEN') }}"
        body: |
          {
            "name": "continuous-docs-generator",
            "gitSource": {
              "type": "github",
              "repo": "YOUR_USERNAME/continuous-docs-generator",
              "ref": "main"
            }
          }

triggers:
  # Run every Monday at 9 AM
  - id: weekly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * 1"

  # Can also trigger manually via API
  - id: manual_trigger
    type: io.kestra.plugin.core.trigger.Webhook
